//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by VideoRouter.rc
//
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDS_NO_CONNECTION               101
#define IDP_SOCKETS_INIT_FAILED         104
#define IDS_RICHEDIT2_INIT_FIALED       105
#define IDB_WRITESMALL                  110
#define IDB_WRITELARGE                  111
#define IDB_MAIN                        112
#define IDB_BUTTONS                     113
#define IDB_FILELARGE                   114
#define IDB_FILESMALL                   115
#define IDR_POPUP_EDIT                  119
#define ID_STATUSBAR_PANE1              120
#define ID_STATUSBAR_PANE2              121
#define IDS_STATUS_PANE1                122
#define IDS_STATUS_PANE2                123
#define IDR_MAINFRAME                   128
#define IDR_MAINFRAME_256               129
#define IDR_VideoRouterTYPE             130
#define IDR_PASTE_MENU                  151
#define IDR_WINDOWS_MENU                152
#define ID_VIEW_NAVIGATION              185
#define IDB_PAGES                       188
#define IDB_PAGES_HC                    189
#define IDB_PAGES_SMALL                 190
#define IDB_PAGES_SMALL_HC              191
#define IDR_THEME_MENU                  200
#define ID_SET_STYLE                    201
#define ID_VIEW_APPLOOK_WIN_2000        210
#define ID_VIEW_APPLOOK_OFF_XP          211
#define ID_VIEW_APPLOOK_WIN_XP          212
#define ID_VIEW_APPLOOK_OFF_2003        213
#define ID_VIEW_APPLOOK_VS_2005         214
#define ID_VIEW_APPLOOK_OFF_2007_BLUE   215
#define ID_VIEW_APPLOOK_OFF_2007_BLACK  216
#define ID_VIEW_APPLOOK_OFF_2007_SILVER 217
#define ID_VIEW_APPLOOK_OFF_2007_AQUA   218
#define ID_TOOLS_OPTIONS                220
#define ID_VIEW_CAPTION_BAR             221
#define ID_VIEW_TASK_BAR                222
#define IDB_INFO                        230
#define IDS_CAPTION_BUTTON              231
#define IDS_CAPTION_BUTTON_TIP          232
#define IDS_CAPTION_TEXT                233
#define IDS_CAPTION_IMAGE_TIP           234
#define IDS_CAPTION_IMAGE_TEXT          235
#define IDS_MYCALENDARS                 250
#define IDS_CALENDAR                    251
#define IDS_SHORTCUTS                   252
#define IDS_FOLDERS                     253
#define IDS_OUTLOOKBAR                  258
#define IDS_RIBBON_FILE                 260
#define IDS_RIBBON_NEW                  262
#define IDS_RIBBON_OPEN                 263
#define IDS_RIBBON_SAVE                 264
#define IDS_RIBBON_SAVEAS               265
#define IDS_RIBBON_PRINT                266
#define IDS_RIBBON_PRINT_LABEL          267
#define IDS_RIBBON_PRINT_QUICK          268
#define IDS_RIBBON_PRINT_PREVIEW        269
#define IDS_RIBBON_PRINT_SETUP          270
#define IDS_RIBBON_CLOSE                271
#define IDS_RIBBON_RECENT_DOCS          272
#define IDS_RIBBON_EXIT                 273
#define IDS_RIBBON_HOME                 274
#define IDS_RIBBON_CLIPBOARD            275
#define IDS_RIBBON_PASTE                276
#define IDS_RIBBON_CUT                  277
#define IDS_RIBBON_COPY                 278
#define IDS_RIBBON_SELECTALL            279
#define IDS_RIBBON_WINDOW               284
#define IDS_RIBBON_WINDOWS              285
#define IDS_RIBBON_STYLE                286
#define IDS_RIBBON_STYLE_TIP            287
#define IDS_RIBBON_STYLE_DESC           288
#define IDS_RIBBON_STATUSBAR            289
#define IDS_RIBBON_VIEW                 290
#define IDS_RIBBON_CAPTIONBAR           295
#define ID_TOOLBOXFOLDER_PROPERTYPANES  300
#define ID_TOOLBOXFOLDER_DATA           301
#define ID_TOOLBOXFOLDER_COMPONENTS     302
#define ID_TOOLBOXFOLDER_WINDOWSFORMS   303
#define ID_TOOLBOXFOLDER_CLIPBOARDRING  304
#define ID_TOOLBOXFOLDER_GENERAL        305
#define IDS_EDIT_MENU                   306
#define IDR_MENU_SOURCE_PROPERY         307
#define IDC_CURSOR_SPLIT                310
#define IDB_RIBBON_BUTTONS              311
#define IDB_CATEGORY_MAIN_LARGE         312
#define IDB_CATEGORY_MAIN_SMALL         313
#define IDB_CATEGORY_MANAGE_LARGE       314
#define IDB_CATEGORY_MANAGE_SMALL       315
#define IDB_BITMAP_LOG                  316
#define IDI_ICON_BOARD                  317
#define IDI_ICON_EXCEL                  318
#define IDI_ICON_FILE                   319
#define IDI_ICON_GRAPH                  320
#define IDI_ICON_MEDIA                  321
#define IDI_ICON_STRUCT                 322
#define IDI_ICON_VISO                   323
#define IDI_ICON_WINDOWS                324
#define IDI_ICON_WORD                   325
#define IDB_MENU_SRC_VGA                326
#define IDB_MENU_SRC_CHAR               327
#define IDB_MENU_SRC_EDID               328
#define IDB_MENU_SRC_RENAME             329
#define IDR_MultiDocAppTYPE             330
#define IDB_NODEIMAGE_ORDERDETAILS      331
#define IDD_DLG_SCENE_MANAGER           350
#define IDD_DLG_COMMUNICATE_CFG         351
#define IDD_DLG_PORT_CONFIG             352
#define IDD_DLG_TEST_PATTERN            353
#define IDD_DLG_TIMING_EDIT             354
#define IDD_DLG_RENAME                  355
#define IDD_DLG_SOURCE_PROPERTY         356
#define IDD_DLG_OSD_DESIGNER            357
#define IDD_DLG_SCENE_LOOP              358
#define IDD_DLG_LOGIN                   359
#define IDD_SPLICEVIEW                  360
#define IDD_DLG_MACHINE_PANEL           361
#define IDD_DLG_SPLICE_SET              362
#define IDB_BMP_ALIGN                   363
#define IDB_BMP_CLOSE                   364
#define IDB_BMP_MAX                     365
#define IDB_BMP_RESTORE                 366
#define IDD_DLG_WND_PROPERTY            367
#define IDI_ICON_NOSIGNAL               368
#define IDI_ICON_SIGNAL                 369
#define IDB_BMP_MONITOR16               370
#define IDI_ICON_MONITOR                371
#define IDB_BMP_MONITOR32               373
#define IDB_BMP_MONITOR_MASK            374
#define IDI_ICON_WINDOW_LOCKED          375
#define IDD_DLG_WAITING                 376
#define IDD_DLG_USER_MANAGE             377
#define IDD_DLG_BACKUP                  378
#define IDI_ICON_KEY                    379
#define IDI_ICON_SUPERADMIN             380
#define IDB_PNG_USER16                  381
#define IDB_PNG_USER_REMOVE16           382
#define IDB_PNG_USER_EDIT16             383
#define IDB_PNG_USER_ADD16              384
#define IDB_PNG_USER_ACCEPT16           385
#define IDB_PNG_ADMIN16                 386
#define IDI_ICON_GENERAL_USER           387
#define IDI_ICON2                       388
#define IDI_ICON_ADMIN                  388
#define IDB_BMP_BACKNRESTORE            389
#define IDB_BMP_BACKUP                  389
#define IDB_PNG_TOP_BORDER              390
#define IDB_PNG2                        391
#define IDB_PNG_LOADING                 391
#define IDC_OUTLOOKBAR_TREE1            1000
#define IDC_OUTLOOKBAR_TREE2            1001
#define IDC_OUTLOOKBAR_LIST1            1002
#define IDC_COLORBTN_PATTERN_BK_COLOR   1005
#define IDC_COLORBTN_FORGND_COLOR       1005
#define IDC_BTN_CANCEL_TEST             1006
#define IDC_BTN_DEFAULT1                1007
#define IDC_BTN_DETECT1                 1008
#define IDC_BTN_APPLY1                  1009
#define IDC_BTN_DEFAULT2                1010
#define IDC_BTN_AUTO_SAMPLE             1011
#define IDC_BTN_APPLY_SAMPLE            1012
#define IDC_BTN_SET_COLORSPACE          1013
#define IDC_GBOX_BRIGHT_CONTRAST        1014
#define IDC_LABEL_BRIGHTNESS            1015
#define IDC_LABEL_CONTRAST              1016
#define IDC_GBOX_SAMPLE                 1017
#define IDC_RADIO_NET_SEL               1018
#define IDC_LABEL_SAMPLE_LEFTPOS        1018
#define IDC_RADIO_COM_SEL               1019
#define IDC_LABEL_SAMPLE_TOPPOS         1019
#define IDC_LABEL_SAMPLE_WIDTH          1020
#define IDC_IP_ADDR                     1021
#define IDC_LABEL_SAMPLE_HEIGHT         1021
#define IDC_CBOX_COMPORT                1022
#define IDC_BTN_DETECT_SAMPLE           1022
#define IDC_BTN_HOST_SEARCH             1023
#define IDC_BTN_ADVANCE_NETCFG          1025
#define IDC_IP_NEW_IPADDR               1026
#define IDC_IP_NEW_MASKADDR             1027
#define IDC_IP_NEW_GATEWAYADDR          1028
#define IDC_MASKEDIT_MACADDR            1029
#define IDC_LIST_HOST_ADDR              1030
#define IDC_BTN_NET_DETECT              1031
#define IDC_BTN_NET_APPLY               1032
#define IDC_BTN_PORT_CFG_APPLY          1033
#define IDC_BTN_PORT_CFG_ALL            1034
#define IDC_BTN_PORT_CFG_NONE           1035
#define IDC_BTN_PORT_CFG_INVERT         1036
#define IDC_SLIDER_PORT_RESOLUTION      1037
#define IDC_CBOX_PORT_CFG_HZ            1038
#define IDC_LIST_OUT_CFG_CHANNEL        1039
#define IDC_BTN_GET_SLAVE_TIMING        1040
#define IDC_BTN_ADD_TIMING              1041
#define IDC_BTN_ALL                     1041
#define IDC_BTN_DEL_TIMING              1042
#define IDC_BTN_NON                     1042
#define IDC_BTN_EDIT_TIMING             1043
#define IDC_BTN_INVERT                  1043
#define IDC_GBOX_CONNECTION             1044
#define IDC_GBOX_CONNECT_SETTING        1045
#define IDC_GBOX_NEW_NETCONFIG          1046
#define IDC_LABEL_DEV_IP                1047
#define IDC_LABEL_DEV_COM               1048
#define IDC_LABEL_NEW_IP                1049
#define IDC_LABEL_NEW_MASK              1050
#define IDC_LABEL_NEW_GATEWAY           1051
#define IDC_LABEL_NEW_MAC               1052
#define IDC_BTN_CONNECT                 1054
#define IDC_BTN_PORT_RESET              1055
#define IDC_BTN_PORT_RESET_ALL          1056
#define IDC_LABEL_SELECTED_RESOLUTION   1057
#define IDC_LABEL_PORT_TIP1             1058
#define IDC_LIST_SCENE                  1060
#define IDC_CBOXEx_SCENE_ICON           1061
#define IDC_EDIT_SCENE_NAME             1062
#define IDC_CHECK_QUICK_MENU            1063
#define IDC_BTN_SCENE_DELETE            1064
#define IDC_EDIT_SCENE_ID               1068
#define IDC_EDIT_SCENE_SAVENAME         1069
#define IDC_TEXT_SCENE_ID               1071
#define IDC_LABEL_SCENE_SAVENAME        1072
#define IDC_GBOX_SCENE_LIST             1073
#define IDC_GBOX_SCENE_OPERATOR         1074
#define IDC_LABEL_SCENE_ICON            1075
#define IDC_LABEL_SCENE_NEWNAME         1076
#define IDC_SEPARATOR_SCENE_MANAGER     1077
#define IDC_EDIT_PATTERN_GRIDLINE_WID   1085
#define IDC_CBOX_PATTERN_GRIDLINE_WID   1086
#define IDC_EDIT_PATTERN_HORZ_SPACE     1087
#define IDC_EDIT_PATTERN_VERT_SPACE     1088
#define IDC_CBOX_PATTERN_HORZ_SPACE     1089
#define IDC_CBOX_PATTERN_VERT_SPACE     1090
#define IDC_BTN_PATTERN_TEST            1091
#define IDC_CHECK_HAS_GRID_PATTERN      1092
#define IDC_COLORBTN_GRIDLINE_COLOR     1093
#define IDC_GBOX_PATTERN_PREVIEW        1094
#define IDC_GBOX_PATTERN_DESIGN         1095
#define IDC_PIC_PATTERN_PREVIEW         1096
#define IDC_LABEL_PATTERN_BK_COLOR      1097
#define IDC_LABEL_PATTERN_GRID_START_POS 1098
#define IDC_LABEL_PATTERN_HORZ_SPACE    1099
#define IDC_LABEL_PATTERN_GRIDLINE_WID  1100
#define IDC_LABEL_PATTERN_GRIDLINE_COLOR 1101
#define IDC_LABEL_PATTERN_VERT_SPACE    1102
#define IDC_EDIT_GRID_START_POSX        1103
#define IDC_EDIT_GRID_START_POSY        1104
#define IDC_EDIT_MAC_ADDR               1106
#define IDC_LIST_PORTS                  1108
#define IDC_SPIN_SCENE_ID               1109
#define IDC_SPIN_HACTIVE                1109
#define IDC_EDIT_HACTIVE                1110
#define IDC_EDIT_VACTIVE                1111
#define IDC_EDIT_HZ                     1112
#define IDC_CBOX_SCAN_MODE              1113
#define IDC_EDIT_HACTIVE_DETAIL         1114
#define IDC_EDIT_VACTIVE_DETAIL         1115
#define IDC_EDIT_HFRONT_DETAIL          1116
#define IDC_EDIT_VFRONT_DETAIL          1117
#define IDC_EDIT_HSYNC_DETAIL           1118
#define IDC_EDIT_VSYNC_DETAIL           1119
#define IDC_EDIT_HTOTAL_DETAIL          1120
#define IDC_EDIT_VTOTAL_DETAIL          1121
#define IDC_CBOX_HPOL_DETAIL            1123
#define IDC_CBOX_VPOL_DETAIL            1124
#define IDC_EDIT_HZ_DETAIL              1125
#define IDC_SPIN_VACTIVE                1126
#define IDC_SPIN_HZ                     1127
#define IDC_SPIN_HACTIVE_DETAIL         1128
#define IDC_SPIN_VACTIVE_DETAIL         1129
#define IDC_SPIN_HFRONT_DETAIL          1130
#define IDC_SPIN_VFRONT_DETAIL          1131
#define IDC_SPIN_HSYNC_DETAIL           1132
#define IDC_SPIN_VSYNC_DETAIL           1133
#define IDC_SPIN_HTOTAL_DETAIL          1134
#define IDC_SPIN_VTOTAL_DETAIL          1135
#define IDC_SPIN_HZ_DETAIL              1136
#define IDC_GBOX_DISPLAY_MODE           1138
#define IDC_LABEL_HACTIVE               1139
#define IDC_LABEL_VACTIVE               1140
#define IDC_LABEL_FRESHRATE             1141
#define IDC_LABEL_SCAN_MODE             1142
#define IDC_GBOX_DETAILED_TIMING        1143
#define IDC_LABEL_HORIZON               1144
#define IDC_LABEL_VERTICAL              1145
#define IDC_LABEL_ACTIVE_DETAIL         1146
#define IDC_LABEL_FRONTPORCH_DETAIL     1147
#define IDC_LABEL_SYNCWID_DETAIL        1148
#define IDC_LABEL_TOTAL_DETAIL          1149
#define IDC_LABEL_POLARITY_DETAIL       1150
#define IDC_LABEL_HZ_DETAIL             1151
#define IDC_LABEL_HZ_RANGE_DETAIL       1152
#define IDC_LABEL_PIXCLK_DETAIL         1153
#define IDC_LABEL_PIXCLK_VAL_DETAIL     1154
#define IDC_BTN_RESTORE_TIMING          1155
#define IDC_EDIT_RENAME                 1156
#define IDC_LABEL_RENAME                1157
#define IDC_GBOX_PORT_LIST              1163
#define IDC_SLIDER_SRC_LIGHTNESS        1164
#define IDC_SLIDER_SRC_CONTRAST         1165
#define IDC_SLIDER_SRC_PHASE            1166
#define IDC_SLIDER_SRC_SAMPLE_LEFT      1167
#define IDC_SLIDER_SRC_SAMPLE_TOP       1168
#define IDC_SLIDER_SRC_SAMPLE_WIDTH     1169
#define IDC_SLIDER_SRC_SAMPLE_HEIGHT    1170
#define IDC_SLIDER_SRC_FREQUENCY        1171
#define IDC_SLIDER_SRC_COLOR_R          1172
#define IDC_SLIDER_SRC_COLOR_G          1173
#define IDC_SLIDER_SRC_COLOR_B          1174
#define IDC_GBOX_LIGHTNESS              1175
#define IDC_GBOX_CONTRAST               1176
#define IDC_GBOX_PHASE                  1177
#define IDC_GBOX_SAMPLE_LEFT            1178
#define IDC_GBOX_SAMPLE_TOP             1179
#define IDC_GBOX_COLOR                  1180
#define IDC_GBOX_FREQUENCY              1181
#define IDC_GBOX_SAMPLE_WIDTH           1182
#define IDC_GBOX_SAMPLE_HEIGHT          1183
#define IDC_EDIT_SRC_LIGHTNESS          1184
#define IDC_EDIT_SRC_CONTRAST           1185
#define IDC_EDIT_SRC_PHASE              1186
#define IDC_EDIT_SRC_SAMPLE_LEFT        1187
#define IDC_EDIT_SRC_SAMPLE_TOP         1188
#define IDC_EDIT_SRC_COLOR_R            1189
#define IDC_EDIT_SRC_COLOR_G            1190
#define IDC_EDIT_SRC_COLOR_B            1191
#define IDC_EDIT_SRC_FREQUENCY          1192
#define IDC_EDIT_SRC_SAMPLE_WIDTH       1193
#define IDC_EDIT_SRC_SAMPLE_HEIGHT      1194
#define IDC_CBOX_COLOR_SPACE_MODE       1195
#define IDC_GBOX_COLOR_SPACE            1196
#define IDC_RICHEDIT_OSD_STRING         1199
#define IDC_COLORBTN_BACKGND_COLOR      1202
#define IDC_MFCBTN_FONTDLG              1203
#define IDC_EDIT_OSD_POS_LEFT           1204
#define IDC_EDIT_OSD_POS_TOP            1205
#define IDC_SPIN_OSD_POS_LEFT           1206
#define IDC_SPIN_OSD_POS_TOP            1207
#define IDC_CBOX_OSD_OVERLAPPED         1208
#define IDC_GBOX_OSD_STRING             1209
#define IDC_GBOX_STRING_FORMAT          1210
#define IDC_GBOX_OSD_POS                1211
#define IDC_GBOX_OSD_OVERLAPPED         1212
#define IDC_LABEL_OSD_FOREGND_COLOR     1213
#define IDC_LABEL_OSD_BACKGND_COLOR     1214
#define IDC_LABEL_OSD_POS_LEFT          1215
#define IDC_LABEL_OSD_POS_TOP           1216
#define IDC_LIST_SCENE_TOUR             1219
#define IDC_BTN_LIST_UP                 1221
#define IDC_BTN_LIST_DOWN               1222
#define IDC_BTN_LIST_TOP                1223
#define IDC_BTN_LIST_BOTTOM             1224
#define IDC_EDIT_TIME_H                 1230
#define IDC_EDIT_TIME_M                 1231
#define IDC_EDIT_TIME_S                 1232
#define IDC_SPIN_TIME_H                 1233
#define IDC_SPIN_TIME_M                 1234
#define IDC_SPIN_TIME_S                 1235
#define IDC_GBOX_ORDER_SET              1236
#define IDC_GBOX_TIME_SET               1237
#define IDC_LIST_PATTERN_OUTPUT         1238
#define IDC_BTN_PATTERN_PREVIEW         1239
#define IDC_BTN_PATTERN_ALL             1240
#define IDC_BTN_PATTERN_NON             1241
#define IDC_BTN_PATTERN_INVERT          1242
#define IDC_SEPARATOR                   1243
#define IDC_GBOX_PATTERN_OUTPUT         1244
#define IDC_CBOX_USER_NAME              1245
#define IDC_EDIT_USER_PASSWORD          1246
#define IDC_LABEL_USER_NAME             1247
#define IDC_LABEL_USER_PASSWORD         1248
#define IDC_LABEL_SRC_CLR_R             1249
#define IDC_LABEL_SRC_CLR_G             1250
#define IDC_LABEL_SRC_CLR_B             1251
#define IDC_LABEL_LOOP_HOUR             1252
#define IDC_LABEL_LOOP_MINUTE           1253
#define IDC_LABEL_LOOP_SECOND           1254
#define IDC_LABEL_HZ                    1255
#define IDC_LABEL_RECENT_TIMING         1256
#define IDC_MESSAGE_ICON                1257
#define IDC_PIC_MSGTEXT                 1260
#define IDAPPLY                         1261
#define IDC_GBOX_RESOLUTION             1262
#define IDC_GBOX_MONITOR_SETUP          1263
#define IDC_LABEL_MONITOR_REFRESHRATE   1264
#define IDC_PIC_PANEL_VIEW              1270
#define IDC_SLIDER_SPLICE_TIMING        1271
#define IDC_EDIT_PHY_HORZ_SCREEN        1272
#define IDC_EDIT_PHY_VERT_SCREEN        1273
#define IDC_EDIT_LOG_HORZ_SCREEN        1274
#define IDC_EDIT_LOG_VERT_SCREEN        1275
#define IDC_SPIN_PHY_HORZ_SCREEN        1276
#define IDC_SPIN_PHY_VERT_SCREEN        1277
#define IDC_SPIN_LOG_HORZ_SCREEN        1278
#define IDC_SPIN_LOG_VERT_SCREEN        1279
#define IDC_BTN_SPLICE_ADD              1280
#define IDC_BTN_SPLICE_DEL              1281
#define IDC_BTN_SPLICE_MOD              1282
#define IDC_LABEL_SPLICE_TIMING         1283
#define IDC_LABEL_PHY_SCREEN            1284
#define IDC_LABEL_LOG_SCREEN            1285
#define IDC_EDIT_WND_NAME               1289
#define IDC_EDIT_WND_POS_X              1290
#define IDC_EDIT_WND_POS_Y              1291
#define IDC_EDIT_WND_SIZE_CX            1292
#define IDC_EDIT_WND_SIZE_CY            1293
#define IDC_LIST_WINDOWS                1294
#define IDC_LABEL_WND_NAME              1295
#define IDC_LABEL_WND_POS               1296
#define IDC_LABEL_WND_SIZE              1297
#define IDC_SPIN_WND_POS_X              1298
#define IDC_SPIN_WND_POS_Y              1299
#define IDC_SPIN_WND_SIZE_CX            1300
#define IDC_SPIN_WND_SIZE_CY            1301
#define IDC_BTN_WND_PROPERTY_APPLY      1302
#define IDC_LABEL_BKG_INFO              1304
#define IDC_PIC_SCREEN_COMBINE          1305
#define IDC_BTN_WND_PROPERTY_ACTIVE     1306
#define IDC_TAB_PORT                    1307
#define IDC_BTN_PATTERN_PRINT_OSD       1308
#define IDC_BTN_PATTERN_CANCEL_OSD      1309
#define IDC_LIST_PATTERN_INPUT          1310
#define IDC_BTN_SCENE_LOCALFILE         1315
#define IDC_EDIT_SCREEN_SPACE_HORZ      1316
#define IDC_EDIT_SCREEN_SPACE_VERT      1317
#define IDC_SPIN_SCREEN_SPACE_HORZ      1318
#define IDC_SPIN_SCREEN_SPACE_VERT      1319
#define IDC_BTN_UPDATE_GRIDLINE         1320
#define IDC_LIST_SCREENS                1323
#define IDC_EDIT_SCREEN_POS_X           1324
#define IDC_EDIT_SCREEN_POS_Y           1325
#define IDC_EDIT_SCREEN_WIDTH           1326
#define IDC_EDIT_SCREEN_HEIGHT          1327
#define IDC_SPIN_SCREEN_POS_X           1328
#define IDC_SPIN_SCREEN_POS_Y           1329
#define IDC_SPIN_SCREEN_WIDTH           1330
#define IDC_SPIN_SCREEN_HEIGHT          1331
#define IDC_RADIO_SIMPLY                1332
#define IDC_RADIO_COMPLEX               1333
#define IDC_RADIO_CUSTOMIZE             1334
#define IDC_BTN_APPLY_SCREEN_SETTINGS   1335
#define IDC_LABEL_REGULAR_SPLICE        1336
#define IDC_EDIT_BLEND_WID_HORZ         1337
#define IDC_EDIT_BLEND_WID_VERT         1338
#define IDC_SPIN_BLEND_WID_HORZ         1339
#define IDC_SPIN_BLEND_WID_VERT         1340
#define IDC_SCROLLBAR_SPLICE_HORZ       1341
#define IDC_SCROLLBAR_SPLICE_VERT       1342
#define IDC_LABEL_RECENT_RES_NAME       1347
#define IDC_BTN_WND_PROPERTY_LOCK       1349
#define IDC_LIST_USER                   1350
#define IDC_EDIT_USER_NAME              1351
#define IDC_EDIT_USER_PWD               1352
#define IDC_EDIT_USER_PWD_REPEAT        1353
#define IDC_CBOX_USER_AUTHORITY         1354
#define IDC_BTN_ADD_USER                1355
#define IDC_BTN_EDIT_USER               1356
#define IDC_BTN_SAVE_USER               1357
#define IDC_BTN_DEL_USER                1358
#define IDC_LABEL_SUMMERY               1359
#define IDC_CHECK_HARDWARE_PARAM        1360
#define IDC_CHECK_CUSTOM_PARAM          1361
#define IDC_CHECK_SOFTWARE_PARAM        1362
#define ID_WRITE_PASTEASHYPERLINK       32770
#define ID_VGA_PROPERTY                 32771
#define ID_CHARACTER_STICK              32772
#define ID_LOAD_EDID                    32773
#define ID_RENAME                       32774
#define ID_RECHECK_SIGNAL               32775
#define ID_RIBBON_CMD_BEGIN             32900
#define ID_RIBBON_CMD_CONNECT           32900
#define ID_RIBBON_CMD_SC_LOAD           32901
#define ID_RIBBON_CMD_SC_SAVE           32902
#define ID_RIBBON_CMD_REFRESH           32903
#define ID_RIBBON_CMD_SC_LOOP           32904
#define ID_RIBBON_CMD_SC_MANAGE         32905
#define ID_RIBBON_CMD_LANG              32906
#define ID_RIBBON_CMD_INPUT_SETUP       32907
#define ID_RIBBON_CMD_OUTPUT_SETUP      32908
#define ID_RIBBON_CMD_IMAGE_TEST        32909
#define ID_RIBBON_CMD_BACKUP            32910
#define ID_RIBBON_CMD_RESTORE           32911
#define ID_RIBBON_CMD_POWER             32912
#define ID_RIBBON_CMD_USER              32913
#define ID_RIBBON_CMD_WND_NEW           32914
#define ID_RIBBON_CMD_WND_CLOSE         32915
#define ID_RIBBON_CMD_WND_CLOSE_ALL     32916
#define ID_RIBBON_CMD_WND_PROPERTY      32917
#define ID_RIBBON_CMD_WND_TOP           32918
#define ID_RIBBON_CMD_WND_BOTTOM        32919
#define ID_RIBBON_CMD_WND_FRONT         32920
#define ID_RIBBON_CMD_WND_BACK          32921
#define ID_RIBBON_CMD_WND_LOCKALL       32922
#define ID_RIBBON_CMD_SPLIT_SET         32923
#define ID_RIBBON_CMD_WND_LOCK          32924
#define ID_RIBBON_CMD_SHOW_GRID         32925
#define ID_RIBBON_CMD_FILL_ANCHORED_SCREEN 32926
#define ID_RIBBON_CMD_FILL_ACROSSED_SCREEN 32927
#define ID_RIBBON_CMD_BTN_ZOOM          32928
#define ID_RIBBON_CMD_SLIDER_ZOOM       32929
#define ID_RIBBON_CMD_USER_CHANGE       32930
#define ID_RIBBON_CMD_RESET             32931
#define ID_SCENE_ID_BEGIN               35000
#define ID_SCENE_ID_END                 35127

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        392
#define _APS_NEXT_COMMAND_VALUE         33000
#define _APS_NEXT_CONTROL_VALUE         1363
#define _APS_NEXT_SYMED_VALUE           333
#endif
#endif
