//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by MVintergrationController.rc
//
#define IDD_DLG_MAINFRAME               102
#define IDP_SOCKETS_INIT_FAILED         103
#define IDC_MG_TABCONTROL               110
#define IDC_HDMI_TABCONTROL             111
#define IDR_MAINFRAME                   128
#define IDB_BITMAP_BOARDSTATE           129
#define IDI_ICON_CFG                    131
#define IDI_ICON_RESET                  132
#define IDC_CHECK                       133
#define IDC_CHECK_NONE                  134
#define IDB_STATE_IMAGES                135
#define IDD_DLG_CONNECT                 137
#define IDB_BITMAP_BACK                 138
#define IDD_DLG_MV                      139
#define IDB_TAB_ICON                    140
#define IDI_ICON_NET                    141
#define IDI_NET_CONN                    142
#define IDI_COM_CONN                    143
#define IDI_ICON_RESETDOWN              145
#define IDD_DLG_PROGRESSBAR             150
#define IDD_DLG_MG                      151
#define IDD_DLG_MG_TIMING               152
#define IDB_BITMAP_MG_TAP               153
#define IDD_DLG_MG_COLOR                156
#define IDD_DLG_MG_BLEND                159
#define IDB_BITMAP_LIGHTOFF             163
#define IDB_BITMAP_LIGHTON              164
#define IDD_DLG_MG_GEOMETRIC            165
#define IDD_DLG_MG_BLACKLVL             166
#define IDD_DLG_MG_FILTER               167
#define IDB_BITMAP_FILTER               170
#define IDI_USB_CONN                    171
#define IDI_ICON_REFRESH                176
#define IDD_DLG_MG_GRIDWARP             177
#define IDI_ICON_UPDATE                 178
#define IDI_ICON_REDO                   184
#define IDI_ICON_UNDO                   185
#define IDI_ICON_CONVERT                187
#define IDI_ICON_SAVE                   189
#define IDI_ICON_DOUBLE_COL             190
#define IDD_DIALOG_ADVANCED_BLENDPARAM  191
#define IDD_DLG_MG_ADVANCED_BLEND       191
#define IDI_ICON_HALF_COL               191
#define IDI_ICON_HALF_ROW               192
#define IDI_ICON_DOUBLE_ROW             193
#define IDI_ICON_AJUST_TYPE             194
#define IDR_MENU_GRIDWARP_STYLE         195
#define IDR_MENU_GRIDWARP_SAVE          196
#define IDR_MENU_GRIDWARP_SELECT        197
#define IDD_DLG_MVX_MAIN                198
#define IDD_DLG_MVX_WNDPROPERTY         199
#define IDB_BITMAP_EXIT_FOCUS           200
#define IDB_BITMAP_EXIT_NORM            201
#define IDB_BITMAP_MAX_FOCUS            202
#define IDB_BITMAP_MAX_NORM             203
#define IDB_BITMAP_RESIZE_FOCUS         204
#define IDB_BITMAP_RESIZE_NORM          205
#define IDB_BITMAP_RESTORE_FOCUS        206
#define IDB_BITMAP_RESTORE_NORM         207
#define IDD_DLG_MVX_BKGSETTING          208
#define IDR_MENU_MVX_SCENE_MANAGE       210
#define IDD_DLG_MVX_VIDEOPROPERTY       211
#define IDR_MENU_MVX_WND_OPTION         212
#define IDD_D                           216
#define IDD_MSGTIPDLG                   216
#define IDB_BITMAP1                     221
#define IDB_BITMAP_TREEBK               221
#define IDD_DLG_HDMI_3D                 222
#define IDD_DLG_HDMI3D                  222
#define IDD_DLG_HDMI_TIMING             223
#define IDD_DLG_HDMI_3DSETTING          224
#define IDC_TREE_BOARD                  1000
#define IDC_PIC_COMMUNICATE             1001
#define IDC_PIC_FUNC                    1002
#define IDC_TOOLBTN_CFG                 1006
#define IDC_TOOLBTN_REFRESH             1007
#define IDC_TOOLBTN_RESET               1008
#define IDC_TOOLBTN_FOUR                1009
#define IDC_TOOLBTN_FIVE                1010
#define IDC_BUTTON_CONNECT              1019
#define IDC_BUTTON_COM                  1021
#define IDC_IPADDRESS_CUR_IP            1022
#define IDC_COMBO_COM                   1023
#define IDC_BUTTON_ADVANCED_NET         1024
#define IDC_IPADDRESS_NEW_IP            1025
#define IDC_IPADDRESS_NEW_MASK          1026
#define IDC_IPADDRESS_NEW_GATEWAY       1027
#define IDC_EDIT_MAC                    1028
#define IDC_BUTTON_APPLAY_NET           1029
#define IDC_BUTTON_NET                  1030
#define IDC_SPLITTER_CONNECT            1031
#define IDC_TEXT_CONNECT_STATE          1032
#define IDC_TEXT_COMMUNICATION_TYPE     1033
#define IDC_TEXT_TPYE                   1034
#define IDC_TEXT_CONNECT_PARAM          1035
#define IDC_BUTTON_DETECT_NET           1036
#define IDC_CBOX_DEF_LAYOUT             1037
#define IDC_CBOX_SEC_LAYOUT             1038
#define IDC_CBOX_THD_LAYOUT             1039
#define IDC_CBOX_DEF_TIMING             1040
#define IDC_CBOX_SEC_TIMING             1041
#define IDC_CBOX_THD_TIMING             1042
#define IDC_BTN_SET_MV_TIMING           1043
#define IDC_CBOX_ADAPTER                1044
#define IDC_BTN_REFRESH                 1045
#define IDC_SEPARATOR1_MV               1046
#define IDC_SEPARATOR2_MV               1047
#define IDC_SEPARATOR3_MV               1048
#define IDC_SEPARATOR4_MV               1049
#define IDC_TEXT_COMB_MODE              1050
#define IDC_TEXT_TIMING_MV              1051
#define IDC_PROGRESS                    1053
#define IDC_TEXT_INFO                   1054
#define IDC_CBOX_COMBMODE               1055
#define IDC_CBOX_TIMING_MG              1056
#define IDC_BTN_TIMINGSET_MG            1057
#define IDC_SEPARATOR1_TIMING_MG        1059
#define IDC_SEPARATOR2_TIMING_MG        1060
#define IDC_TEXT_TIMINGINFO             1061
#define IDC_EDIT_TIMINGINFO             1062
#define IDC_PIC_COLORVIEW               1064
#define IDC_RADIO_SOURCETEST            1065
#define IDC_RADIO_IMAGETEST             1066
#define IDC_RADIO_CANCELBLEND           1067
#define IDC_RADIO_BLACKBLEND            1068
#define IDC_RADIO_RESUMEBLEND           1069
#define IDC_GBOX_TESTMODE               1070
#define IDC_GBOX_BLENDOPT               1071
#define IDC_GBOX_AJUSTMETHOD            1073
#define IDC_RADIO_LINEAR                1074
#define IDC_RADIO_REGION                1075
#define IDC_RADIO_RED                   1076
#define IDC_RADIO_GREEN                 1077
#define IDC_RADIO_BLUE                  1078
#define IDC_RADIO_WHITE                 1079
#define IDC_BTN_COLOR_RESET             1080
#define IDC_GBOX_COLOR                  1081
#define IDC_ONOFF_INDICATOR             1083
#define IDC_BTN_HIDDEN_LEFTDLG          1084
#define IDC_SEPARATOR_MAIN              1085
#define IDC_BUTTON_SIZEMARK             1086
#define IDC_EDIT_LEFT_BLEND             1087
#define IDC_EDIT_TOP_BLEND              1088
#define IDC_EDIT_RIGHT_BLEND            1089
#define IDC_EDIT_BOTTOM_BLEND           1090
#define IDC_CHECK_LEFT_BLEND            1091
#define IDC_CHECK_TOP_BLEND             1092
#define IDC_CHECK_RIGHT_BLEND           1093
#define IDC_CHECK_BOTTOM_BLEND          1094
#define IDC_RADIO_LEFT_BLEND            1095
#define IDC_RADIO_TOP_BLEND             1096
#define IDC_RADIO_RIGHT_BLEND           1097
#define IDC_RADIO_BOTTOM_BLEND          1098
#define IDC_SPIN_LEFT_BLEND             1099
#define IDC_SPIN_TOP_BLEND              1100
#define IDC_SPIN_RIGHT_BLEND            1101
#define IDC_SPIN_BOTTOM_BLEND           1102
#define IDC_CHECK_ENABLE_BLENDING       1103
#define IDC_RADIO_NON_PUREWHITE         1104
#define IDC_RADIO_PUREWHITE             1105
#define IDC_BTN_SET_WHITELVL            1106
#define IDC_EDIT_WHITELVL               1110
#define IDC_SLIDER_ALPHA                1111
#define IDC_EDIT_ALPHA                  1112
#define IDC_SLIDER_P                    1113
#define IDC_SLIDER_GAMMA                1114
#define IDC_EDIT_P                      1115
#define IDC_EDIT_GAMMA                  1116
#define IDC_BTN_DEF_BLENDPARA           1117
#define IDC_BTN_TEST_BLENDPARA          1118
#define IDC_BTN_SET_BLENDWID            1119
#define IDC_PIC_BK_BLEND                1120
#define IDC_PIC_LEFT_BLEND              1121
#define IDC_PIC_TOP_BLEND               1122
#define IDC_PIC_RIGHT_BLEND             1123
#define IDC_PIC_BOTTOM_BLEND            1124
#define IDC_TEXT_LEFT_BLEND             1125
#define IDC_TEXT_RIGHTBLEND             1126
#define IDC_GBOX_WHITEMODE              1127
#define IDC_TEXT_WHITELVL               1128
#define IDC_GBOX_BLENDPARA              1129
#define IDC_TEXT_ALPHA                  1130
#define IDC_TEXT_P                      1131
#define IDC_TEXT_GAMMA                  1132
#define IDC_TEXT_MIN_ALPHA              1133
#define IDC_TEXT_MAX_ALPHA              1134
#define IDC_TEXT_MIN_P                  1135
#define IDC_TEXT_MAX_P                  1136
#define IDC_TEXT_MIN_GAMMA              1137
#define IDC_TEXT_MAX_GAMMA              1138
#define IDC_BTN_ADVANCED_PARA           1139
#define IDC_GBOX_BLENDWIDTH             1140
#define IDC_PIC_BLACKLVL                1141
#define IDC_BTN_TOPLEFT_BLEND           1142
#define IDC_BTN_TOPRIGHT_BLEND          1143
#define IDC_BTN_BOTTOMLEFT_BLEND        1144
#define IDC_BTN_BOTTOMRIGHT_BLEND       1145
#define IDC_BTN_LEFT_BLEND              1146
#define IDC_BTN_TOP_BLEND               1147
#define IDC_BTN_RIGHT_BLEND             1148
#define IDC_BTN_BOTTOM_BLEND            1149
#define IDC_BTN_LEFT_LEAKAGE            1150
#define IDC_BTN_TOP_LEAKAGE             1151
#define IDC_BTN_RIGHT_LEAKAGE           1152
#define IDC_BTN_BOTTOM_LEAKAGE          1153
#define IDC_BTN_NON_BLEND               1154
#define IDC_GBOX_LEAKAGE_WID            1155
#define IDC_TEXT_HAS_LEAKAGE            1156
#define IDC_RADIO_LEFT_LEAKAGE          1157
#define IDC_RADIO_TOP_LEAKAGE           1158
#define IDC_RADIO_RIGHT_LEAKAGE         1159
#define IDC_RADIO_BOTTOM_LEAKAGE        1160
#define IDC_EDIT_TOPOF_LEFTLEAKAGE      1161
#define IDC_EDIT_LEFTOF_TOPLEAKAGE      1162
#define IDC_EDIT_TOPOF_RIGHTLEAKAGE     1163
#define IDC_EDIT_LEFTOF_BOTTOMLEAKAGE   1164
#define IDC_EDIT_BOTTOMOF_LEFTLEAKAGE   1165
#define IDC_EDIT_RIGHTOF_TOPLEAKAGE     1166
#define IDC_EDIT_BOTTOMOF_RIGHTLEAKAGE  1167
#define IDC_EDIT_RIGHTOF_BOTTOMLEAKAGE  1168
#define IDC_SPIN_TOPOF_LEFTLEAKAGE      1169
#define IDC_SPIN_LEFTOF_TOPLEAKAGE      1170
#define IDC_SPIN_TOPOF_RIGHTLEAKAGE     1171
#define IDC_SPIN_LEFTOF_BOTTOMLEAKAGE   1172
#define IDC_SPIN_BOTTOMOF_LEFTLEAKAGE   1173
#define IDC_SPIN_RIGHTOF_TOPLEAKAGE     1174
#define IDC_SPIN_BOTTOMOF_RIGHTLEAKAGE  1175
#define IDC_SPIN_RIGHTOF_BOTTOMLEAKAGE  1176
#define IDC_BTN_SET_LEAKAGEWID          1177
#define IDC_CHECK_ENABLE_BLACKLVL_TEST  1178
#define IDC_EDIT_TEST_LVLPOS            1179
#define IDC_SPIN_TEST_LVLPOS            1180
#define IDC_BTN_RESET_BLACKLVL          1181
#define IDC_TEXT_TOPOF_LEFTLEAKAGE      1182
#define IDC_TEXT_LEFTOF_TOPLEAKAGE      1183
#define IDC_TEXT_TOPOF_RIGHTLEAKAGE     1184
#define IDC_TEXT_LEFTOF_BOTTOMLEAKAGE   1185
#define IDC_TEXT_BOTTOMOF_LEFTLEAKAGE   1186
#define IDC_TEXT_RIGHTOF_TOPLEAKGE      1187
#define IDC_TEXT_BOTTOMOF_RIGHTLEAKAGE  1188
#define IDC_TEXT_RIGHTOF_BOTTOMLEAKAGE  1189
#define IDC_TEXT_TEST_LVLPOS            1190
#define IDC_CHECK_TESTPOS_FIXED         1191
#define IDC_CHECK_ENABLE_BLACKLVL       1192
#define IDC_GBOX_ENABLE_BLACK           1193
#define IDC_SLIDER_BLUR_VALUE           1195
#define IDC_TEXT_BLUR                   1196
#define IDC_TEXT_BLUREFFECT             1197
#define IDC_PIC_BLUR_EFFICTIVE          1198
#define IDC_TEXT_MIN_BLUR               1199
#define IDC_TEXT_MAX_BLUR               1200
#define IDC_EDIT_BLUR_RADIUS            1201
#define IDC_SPIN_BLUR_RADIUS            1202
#define IDC_BTN_KEYSTONE                1203
#define IDC_BTN_CURVE                   1204
#define IDC_BTN_DENSITY                 1205
#define IDC_PIC_GEO                     1206
#define IDC_BUTTON_USB                  1207
#define IDC_TEXT_IPADDR                 1208
#define IDC_TEXT_SERIALPORT             1209
#define IDC_TEXT_NETWORK_PARAM          1210
#define IDC_TEXT_NEW_IPADDR             1211
#define IDC_TEXT_NEW_SUBNET             1212
#define IDC_TEXT_NEW_GATEWAY            1213
#define IDC_TEXT_NEW_MACADDR            1214
#define IDC_TEXT_DEVLIST_MV             1215
#define IDC_TEXT_RESOLUTIONS_SETTING_MV 1216
#define IDC_TEXT_PREFER_TIMING_MV       1217
#define IDC_TEXT_ALTERNATE_TIMING1_MV   1218
#define IDC_TEXT_ALTERNATE_TIMING2_MV   1219
#define IDC_EDIT_TL_POINT_X             1221
#define IDC_EDIT_TC_POINT_X             1222
#define IDC_EDIT_TC_POINT_Y             1223
#define IDC_EDIT_TR_POINT_X             1224
#define IDC_EDIT_TR_POINT_Y             1225
#define IDC_EDIT_EX1_POINT_Y            1226
#define IDC_EDIT_RC_POINT_Y             1227
#define IDC_EDIT_EX2_POINT_Y            1228
#define IDC_EDIT_BR_POINT_Y             1229
#define IDC_EDIT_BL_POINT_X             1230
#define IDC_EDIT_EX1_POINT_X            1231
#define IDC_EDIT_BC_POINT_X             1232
#define IDC_EDIT_MC_POINT_X             1233
#define IDC_EDIT_BR_POINT_X             1234
#define IDC_EDIT_LC_POINT_Y             1235
#define IDC_EDIT_TL_POINT_Y             1236
#define IDC_EDIT_BL_POINT_Y             1237
#define IDC_EDIT_LC_POINT_X             1238
#define IDC_EDIT_RC_POINT_X             1239
#define IDC_EDIT_MC_POINT_Y             1240
#define IDC_EDIT_BC_POINT_Y             1241
#define IDC_SPIN_TL_POINT_X             1242
#define IDC_SPIN_TC_POINT_X             1243
#define IDC_SPIN_TC_POINT_Y             1244
#define IDC_SPIN_TR_POINT_X             1245
#define IDC_SPIN_TR_POINT_Y             1246
#define IDC_SPIN_BL_POINT_X             1247
#define IDC_SPIN_EX1_POINT_X            1248
#define IDC_SPIN_BC_POINT_X             1249
#define IDC_SPIN_MC_POINT_X             1250
#define IDC_SPIN_BR_POINT_X             1251
#define IDC_SPIN_EX1_POINT_Y            1252
#define IDC_SPIN_RC_POINT_Y             1253
#define IDC_SPIN_EX2_POINT_Y            1254
#define IDC_SPIN_BR_POINT_Y             1255
#define IDC_SPIN_LC_POINT_Y             1256
#define IDC_SPIN_TL_POINT_Y             1257
#define IDC_SPIN_BL_POINT_Y             1258
#define IDC_SPIN_MC_POINT_Y             1259
#define IDC_SPIN_RC_POINT_X             1260
#define IDC_SPIN_LC_POINT_X             1261
#define IDC_SPIN_BC_POINT_Y             1262
#define IDC_BTN_GEO_RESET               1263
#define IDC_PIC_GRIDWARP_VIEW           1265
#define IDC_BTN_DOUBLE_GRID_ROW         1269
#define IDC_BTN_HALF_GRID_ROW           1270
#define IDC_BTN_DOUBLE_GRID_COL         1271
#define IDC_BTN_HALF_GRID_COL           1272
#define IDC_BTN_LOAD_GEOMETRIC_DATA     1273
#define IDC_BTN_UNDO_GRIDWARP           1274
#define IDC_BTN_REDO_GRIDWARP           1275
#define IDC_BTN_RESET_GRIDWARP          1276
#define IDC_BTN_LOAD_AND_SAVE           1277
#define IDC_EDIT_CTRL_PT_X              1282
#define IDC_EDIT_CTRL_PT_Y              1283
#define IDC_COMBO_MOVE_INCREMENT        1284
#define IDC_BTN_SWITCH_AJUST_MODE       1285
#define IDC_CHECK_BLANCE_LEFT           1286
#define IDC_CHECK_BLANCE_UPPER          1287
#define IDC_CHECK_BLANCE_RIGHT          1288
#define IDC_CHECK_BLANCE_DOWN           1289
#define IDC_CHECK_BLANCE_ALL_DIRECTIONS 1290
#define IDC_CHECK_GRID_SMOOTH           1291
#define IDC_GBOX_FUNC_CTRL              1292
#define IDC_GBOX_AJUST_CTRL             1293
#define IDC_GBOX_BLANCE_CTRL            1294
#define IDC_GBOX_CTRL_PT_COORDS         1295
#define IDC_GBOX_GRIDLINES_CTRL         1296
#define IDC_TEXT_CTRL_PT_X              1297
#define IDC_TEXT_CTRL_PT_Y              1298
#define IDC_TEXT_MOVE_INCREMENT         1299
#define IDC_TEXT_GRID_ROW               1300
#define IDC_TEXT_GRID_COLUMN            1301
#define IDC_PIC_MVX                     1308
#define IDC_PIC_MVX_CHART               1309
#define IDC_COMBO_WNDINDEX              1310
#define IDC_EDIT_WNDPOS_X               1311
#define IDC_EDIT_WNDPOS_Y               1312
#define IDC_EDIT_WNDSIZE_WIDTH          1313
#define IDC_EDIT_WNDSIZE_HEIGHT         1314
#define IDC_EDIT_WNDTITLE               1315
#define IDC_TEXT_WNDINDEX               1316
#define IDC_TEXT_WNDTITLE               1317
#define IDC_TEXT_WNDPOS                 1318
#define IDC_TEXT_WNDSIZE                1319
#define IDC_TEXT_WNDPOS_X               1320
#define IDC_TEXT_WNDPOS_Y               1321
#define IDC_TEXT_WNDSIZE_WIDTH          1322
#define IDC_TEXT_WNDSIZE_HEIGHT         1323
#define IDC_CBOX_MVX_BKGTIMING          1324
#define IDC_BTN_MVX_CUSTOMIZE_TIMING    1325
#define IDC_BTN_MVX_SET_BKGTIMING       1326
#define IDC_EDIT_MVX_BKG_HACTIVE        1327
#define IDC_EDIT_MVX_BKG_VACTIVE        1328
#define IDC_EDIT_MVX_BKG_HFRONT         1329
#define IDC_EDIT_MVX_BKG_VFRONT         1330
#define IDC_EDIT_MVX_BKG_HSYNC          1331
#define IDC_EDIT_MVX_BKG_VSYNC          1332
#define IDC_EDIT_MVX_BKG_HTOTAL         1333
#define IDC_EDIT_MVX_BKG_VTOTAL         1334
#define IDC_CBOX_MVX_BKG_HPOL           1335
#define IDC_CBOX_MVX_BKG_VPOL           1336
#define IDC_EDIT_MVX_BKG_FRESHRATE      1337
#define IDC_SPIN_MVX_BKG_FRESHRATE      1338
#define IDC_BTN_MVX_SET_COMBINATION     1339
#define IDC_EDIT_MVX_PHY_HORZ           1340
#define IDC_EDIT_MVX_PHY_VERT           1341
#define IDC_EDIT_MVX_LOG_HORZ           1342
#define IDC_EDIT_MVX_LOG_VERT           1343
#define IDC_TEXT_MVX_BKG_PIXCLOCK       1344
#define IDC_CBOX_SPLITMODE              1345
#define IDC_CBOX_MVX_BKG_SPLITMODE      1345
#define IDC_COMBO1                      1346
#define IDC_CBOX_MVX_VIDEO_TIMING       1346
#define IDC_CBOX_HDMI_INPUTTIMING       1346
#define IDC_CBOX_HDMI_INPUT_3DMODE      1346
#define IDC_BUTTON1                     1347
#define IDC_BTN_MVX_VIDEO_SETTIMING     1347
#define IDC_BTN_CUSTOM_TIMING           1347
#define IDC_BTN_HDMI_SET_INPUT3DMOD     1347
#define IDC_CHECK1                      1348
#define IDC_CHECK_MVX_VIDEO_LIMITSIZE   1348
#define IDC_CHECK2                      1349
#define IDC_CHECK_MVX_VIDEO_LIMITSCALE  1349
#define IDC_CHECK3                      1350
#define IDC_CHECK_MVX_VIDEO_LIMITPOS    1350
#define IDC_BTN_MVX_VIDEO_CUSTOM        1351
#define IDC_EDIT_MVX_VIDEO_HACTIVE      1352
#define IDC_EDIT_MVX_VIDEO_HFRONT       1353
#define IDC_EDIT_MVX_VIDEO_HSYNC        1354
#define IDC_EDIT_MVX_VIDEO_HTOTAL       1357
#define IDC_EDIT_MVX_VIDEO_VACTIVE      1358
#define IDC_EDIT_MVX_VIDEO_VFRONT       1359
#define IDC_EDIT_MVX_VIDEO_VSYNC        1360
#define IDC_EDIT_MVX_VIDEO_VTOTAL       1361
#define IDC_CBOX_MVX_VIDEO_HPOL         1362
#define IDC_CBOX_MVX_VIDEO_VPOL         1363
#define IDC_EDIT_MVX_VIDEO_HZ           1364
#define IDC_SPIN_MVX_VIDEO_HZ           1365
#define IDC_TEXT_MVX_VIDEO_PIXCLK       1366
#define IDC_EDIT_HDMI_HACTIVE           1367
#define IDC_EDIT_HDMI_VACTIVE           1368
#define IDC_EDIT_HDMI_HFRONT            1369
#define IDC_EDIT_HDMI_VFRONT            1370
#define IDC_EDIT_HDMI_HSYNC             1371
#define IDC_EDIT_HDMI_VSYNC             1372
#define IDC_EDIT_HDMI_HTOTAL            1373
#define IDC_EDIT_HDMI_VTOTAL            1374
#define IDC_CBOX_HDMI_HPOL              1375
#define IDC_CBOX_HDMI_VPOL              1376
#define IDC_EDIT_HDMI_HZ                1377
#define IDC_SPIN_HDMI_HZ                1378
#define IDC_BTN_HDMI_SET_INPUTTIMING    1379
#define IDC_CBOX_HDMI_OUTPUTTIMING      1380
#define IDC_GBOX_HDMI_INPUTTIMING       1381
#define IDC_GBOX_HDMI_OUTPUTTIMING      1382
#define IDC_TEXT_HDMI_PIXEL             1383
#define IDC_TEXT_HDMI_PIXEL_VAL         1384
#define IDC_BTN_HDMI_SET_OUTPUTTIMING   1385
#define IDC_CBOX_HDMI_OUTPUT_3DMODE     1386
#define IDC_BTN_HDMI_SET_OUTPUT_3DMODE  1387
#define IDC_CBOX_HDMI_OCTAVE            1388
#define IDC_BTN_HDMI_SET_OCTAVE         1389
#define IDC_CBOX_HDMI_EYE_SWITCH        1390
#define IDC_BTN_HDMI_SWITCH_EYE         1391
#define IDC_GBOX_HDMI_INPUT_3DMODE      1392
#define IDC_GBOX_HDMI_OUTPUT_3DMODE     1393
#define IDC_GBOX_HDMI_OCTAVE            1394
#define IDC_GBOX_HDMI_EYE_SWITCH        1395
#define IDC_TEXT_HDMI_INPUTTIMING       1396
#define IDC_TEXT_HDMI_HACTIVE           1397
#define IDC_TEXT_HDMI_HFRONT            1398
#define IDC_TEXT_HDMI_HSYNC             1399
#define IDC_TEXT_HDMI_HTOTAL            1400
#define IDC_TEXT_HDMI_POL               1401
#define IDC_TEXT_HDMI_FRESH             1402
#define IDC_TEXT_HDMI_HZ                1403
#define IDC_TEXT_HDMI_HORZ              1404
#define IDC_TEXT_HDMI_VERT              1405
#define IDC_TEXT_HDMI_OUTPUTTIMING      1406
#define IDC_TEXT_HDMI_INPUT3D           1407
#define IDC_TEXT_HDMI_OUTPUT3D          1408
#define IDC_TEXT_HDMI_OCTAVE            1409
#define IDC_TEXT_HDMI_EYE               1410
#define IDC_BUTTON2                     1411
#define IDC_BTN_HDMI_CUSTOM_OUT         1411
#define IDC_PICTURE_VIEW                1510
#define IDC_EDIT_LEFTNONIUS_POS         1523
#define IDC_EDIT_LEFTNONIUS_VAL         1524
#define IDC_EDIT_RIGHTNONIUS_POS        1525
#define IDC_EDIT_RIGHTNONIUS_VAL        1526
#define IDC_EDIT_INDIVNONIUS_POS        1527
#define IDC_EDIT_INDIVNONIUS_VAL        1528
#define IDC_SPIN_LEFTNONIUS_POS         1529
#define IDC_SPIN_LEFTNONIUS_VAL         1530
#define IDC_SPIN_RIGHTNONIUS_POS        1531
#define IDC_SPIN_RIGHTNONIUS_VAL        1532
#define IDC_SPIN_INDIVNONIUS_POS        1533
#define IDC_SPIN_INDIVNONIUS_VAL        1534
#define ID_GW_STYLE_KEYSTONE            32780
#define ID_GW_STYLE_INTER_KEYSTONE      32781
#define ID_GW_STYLE_INTERROW            32782
#define ID_GW_STYLE_INTERCOL            32783
#define ID_GW_STYLE_FULLROW             32784
#define ID_GW_STYLE_FULLCOL             32785
#define ID_GW_STYLE_SINGLEPOINT         32786
#define ID_READ_LOCAL_GRIDFILE          32787
#define ID_SAVETO_LOCAL_GRIDFILE        32788
#define ID_LOAD_DEVICE_GRIDDATA         32789
#define ID_SAVETO_DEVICE_GRIDDATA       32790
#define ID_KEYSTONE_SELECT              32799
#define ID_SAVE_SCENE_FILE              32833
#define ID_READ_SCENE_FILE              32834
#define ID_WRITE_DEV_SCENE1             32835
#define ID_WRITE_DEV_SCENE2             32836
#define ID_WRITE_DEV_SCENE3             32837
#define ID_WRITE_DEV_SCENE4             32838
#define ID_WRITE_DEV_SCENE5             32839
#define ID_WRITE_DEV_SCENE6             32840
#define ID_WRITE_DEV_SCENE7             32841
#define ID_WRITE_DEV_SCENE8             32842
#define ID_LOAD_DEV_SCENE1              32843
#define ID_LOAD_DEV_SCENE2              32844
#define ID_LOAD_DEV_SCENE3              32845
#define ID_LOAD_DEV_SCENE4              32846
#define ID_LOAD_DEV_SCENE5              32847
#define ID_LOAD_DEV_SCENE6              32848
#define ID_LOAD_DEV_SCENE7              32849
#define ID_LOAD_DEV_SCENE8              32850
#define ID_MVX_OPEN_WINDOW              32851
#define ID_MVX_CLOSE_WINDOW             32852
#define ID_ZORDER_TOPMOST               32853
#define ID_ZORDER_BOTTOMMOST            32854
#define ID_ZORDER_MOVEFRONT             32855
#define ID_ZORDER_MOVEBACK              32856
#define ID_MVX_SAME_WID                 32857
#define ID_MVX_SAME_HGT                 32858
#define ID_MVX_SAME_SIZE                32859

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        227
#define _APS_NEXT_COMMAND_VALUE         32873
#define _APS_NEXT_CONTROL_VALUE         1412
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
